### ISSUE TITLE
Option to disable use of pid file

### ISSUE THREAD

**Issue by maxb-odessa** [nirenjan/libx52#42]
x52d should have an option to disable use of pid file - this is requied if the daemon is controlled by systemd. Use of pid file often leads to false positive daemon running check. Or pid file on-exit cleanup should be implemented.

Failure example:
# journalctl -xu x52d
...
May 15 16:37:06 flatbox.home x52d[1728]: FATAL: x52d_main.c:122 Daemon is already running as PID 1684
May 15 16:37:06 flatbox.home systemd[1]: x52d.service: Main process exited, code=exited, status=1/FAILURE
...
# ps axu | grep 1684
root        1684  0.0  0.0 229568  4536 ?        SLsl 16:37   0:00 /usr/libexec/low-memory-monitor

**Comment by nirenjan** [comment]
I changed it to no longer read/write the PID file when running in foreground, which is the default in the systemd service file.
