### ISSUE TITLE
FATAL: x52d_main.c:117 Daemon is already running as PID 23488

### ISSUE THREAD

**Issue by MNS26** [nirenjan/libx52#47]
whenever i run any commands it will throw a fatal message (`FATAL: x52d_main.c:117 Daemon is already running as PID 22828`)

when running anything other than `x52d -h` it throws a permission error

when using `sudo x52d` running any command after that (other than `x52d -h`) it will give the "FATAL" error
![image](https://user-images.githubusercontent.com/53867268/209357686-f562eb03-acf3-4cd7-984c-0fa36c344cd7.png)

**Comment by nirenjan** [comment]
Did you install the package from source or the Debian package?

Can you run `ps aux | grep x52d` and share the output. Also the output of `systemctl status x52d` please.

**Comment by MNS26** [comment]
i installed it from the AUR on arch

**Comment by MNS26** [comment]
the output of both 
![image](https://user-images.githubusercontent.com/53867268/209388349-c26833f1-94ce-4ffc-a9a0-32a6b27f2c0b.png)

**Comment by MNS26** [comment]
i can try and install the github version if needed

**Comment by nirenjan** [comment]
For some reason, it looks like the daemon might have crashed earlier and not cleaned up the PID file - look for a file `/var/run/x52d.pid` and if it exists, delete it.

**Comment by nirenjan** [comment]
BTW, this is fixed in the latest version on Github.

**Comment by MNS26** [comment]
there was a pid file yeah... 
i will install the git version them

**Comment by MNS26** [comment]
![image](https://user-images.githubusercontent.com/53867268/209404183-6d3888af-07bf-474b-9897-ba5414aa411c.png)
hmm after install it thew errors and didnt actually install

**Comment by MNS26** [comment]
![image](https://user-images.githubusercontent.com/53867268/209440844-e84deedd-d230-4c24-b984-6bf3b30f60e9.png)
welp installed the github version and its the same thing

**Comment by MNS26** [comment]
![image](https://user-images.githubusercontent.com/53867268/209441030-f5cd537a-60f9-4b0b-ace1-19a85e0602a4.png)
when i killed x52d it shows one with my user but... throws the `fopen: permission denied` message

**Comment by MNS26** [comment]
@nirenjan hmm how does it handle when no x52 is plugged in?

**Comment by nirenjan** [comment]
I did fix #43 in the latest version on Github, so that may be the reason why the 0.2.3 version crashed. I haven't gotten around to making a new release yet though. One thing though, if you installed from Github, you should stick to running it via systemd, that will ensure it runs in foreground mode, rather than background, and it will skip the check for the PID file.

**Comment by nirenjan** [comment]
The daemon is capable of recognizing when no joystick is connected, and it will try to reconnect every 5 seconds or so. If a joystick is connected, then it will update the joystick every 50 ms, and that should detect a disconnection nearly instantly. There was a bug in earlier versions which didn't quite handle the disconnect and reconnect properly, so that's why you should switch to the latest version.

**Comment by nirenjan** [comment]
@MNS26, could you please uninstall the Github version and update to v0.3.0 from AUR? Make sure you cleanup the PID file.

**Comment by MNS26** [comment]
> @MNS26, could you please uninstall the Github version and update to v0.3.0 from AUR? Make sure you cleanup the PID file.

how do i uninstall the git version?
`sudo make uninstall?`

**Comment by MNS26** [comment]
> I did fix #43 in the latest version on Github, so that may be the reason why the 0.2.3 version crashed. I haven't gotten around to making a new release yet though. One thing though, if you installed from Github, you should stick to running it via systemd, that will ensure it runs in foreground mode, rather than background, and it will skip the check for the PID file.

i never had a issue with it (having it plugged in or not when starting the daemon didnt make a difference)

**Comment by nirenjan** [comment]
> > @MNS26, could you please uninstall the Github version and update to v0.3.0 from AUR? Make sure you cleanup the PID file.
> 
> how do i uninstall the git version?
> `sudo make uninstall?`

Yes, `sudo make uninstall `

**Comment by MNS26** [comment]
just did a uninstall and no pid files left

rn installing AUR version
![image](https://user-images.githubusercontent.com/53867268/209582452-8b20100f-b5d0-4ef9-ad85-16fd425c16b2.png)

**Comment by MNS26** [comment]
also for some odd reason Elite Dangerous sees the controls double (still works fine)
![image](https://user-images.githubusercontent.com/53867268/209582530-815cea8a-560c-4b13-902a-deda34870891.png)

**Comment by MNS26** [comment]
oh that reminds me... is there _any_ way to disable the little mouse knob on the throttle?

accidentally bumping it makes the game go nuts (axis 8 & 9) and for some reason i cant seem to assign them in game 
(just a slight bump)
![image](https://user-images.githubusercontent.com/53867268/209582679-9784b922-baff-43eb-9362-8083c3ffbb00.png)

**Comment by MNS26** [comment]
Just finished install
![image](https://user-images.githubusercontent.com/53867268/209582818-de5cb0ab-5efc-4c9a-82e1-03d64216cc1b.png)

**Comment by nirenjan** [comment]
You should already be running x52d from systemd, check `systemctl status x52d.service`. Also, x52d requires root permissions to write to certain directories.

**Comment by MNS26** [comment]
hmm i was kinda hoping to not have to rely on root to access it

after manually starting the service (either via `sudo x52d` or with `systemctl`) it works

on another note... do you have a communication example for sending data _to_ the x52? (planning on replacing it with a RP2040 cus if its 12bit ADC)

**Comment by MNS26** [comment]
hmm idk whats going on but the trigger on the joystick is set to half pressed and T2...
this happened after enabling the service
![image](https://user-images.githubusercontent.com/53867268/210184849-f2bd559e-53f3-483a-9adf-2fe679517f99.png)
</r>
![image](https://user-images.githubusercontent.com/53867268/210184867-913828e6-9f24-478f-a767-5f351ef245b5.png)
i also cant seem to bind axis 7 & 8 (not that i want to)

**Comment by MNS26** [comment]
hmm yeah for whatever reason it now keeps sending wrong inputs

**Comment by MNS26** [comment]
![image](https://user-images.githubusercontent.com/53867268/210186516-b9cc332b-b16a-4c40-ba59-b83d1c822158.png)

the button inputs from top to botton
mid Dpad up
mid Dpad down
mid Dpad left
mid Dpad right
C
B
A
left Dpad right
left Dpad left 

all of those come from the joystick
running `sdl2-jstest -t 0` shows all the correct inputs and buttons tho

its currently 11:45pm ill look into it more tomorrow

**Comment by MNS26** [comment]
welp i think i found the issue... 
i have no clue how this happened but... sees the X52 as a raspberry pi pico instead 
(i did fool with the PID and VID of the pico but its not plugged in)
![image](https://user-images.githubusercontent.com/53867268/210224183-7fde1893-5758-4391-8c58-b778eb5a2011.png)

**Comment by nirenjan** [comment]
I've not played Elite Dangerous, but if I understand correctly, it is running under Wine/Proton, and we need a way to clear its cache of joysticks. I'm sorry I couldn't be of more help here.

**Comment by MNS26** [comment]
i just reinstalled the OS to be sure it wasnt that and its still there so... ill have a look on google

**Comment by MNS26** [comment]
should i install the kernel module for the X52 pro?  (the one in the repo folder)
im running the latest zen kernel

**Comment by nirenjan** [comment]
No, the kernel module is no longer needed. Glad you found the problem with the bindings

**Comment by MNS26** [comment]
hmm weird... cus it sees the mouse X and Y axis as a joystick and making proton go ballistic 
but with it it doesnt but... itt indeed causes the buttons to be rearranged and thus a not so happy game
with the module
![image](https://user-images.githubusercontent.com/53867268/210397991-41bfb77b-8331-44d3-bb1c-aff39db5ab1d.png)
 
 without the module
 
![image](https://user-images.githubusercontent.com/53867268/210398149-54cdc7c9-c470-4a03-837c-53fe28efe0f5.png)

those 2 extra axis cause nearly all the buttons to be in the pressed state to proton... 
is there a way to preserve the button layout but remove the 2 axis? (they are mapped to mouse with the `x52d.service`)

**Comment by nirenjan** [comment]
You don't need the kernel module at all - it was an exercise in learning kernel module programming way back, I will remove it, since it's no longer needed in any recent kernel. `x52d` does not use the kernel provided events, it interprets the data directly from the raw USB report provided by `hidraw`.

For the mouse, the axis themselves are handled by the kernel, `x52d` just uses the events to trigger virtual mouse events, that is, the mouse can be controlled in Linux using the thumbstick. You can disable it by editing `/etc/x52d/x52d.conf` and reloading the daemon - `systemctl reload x52d.service`

**Comment by MNS26** [comment]
the mouse indeed works with the `x52d.service` BUT... it also shows up as axis 7 and 8 and proton gets VERY confused about the button presses.
with the kernel module the mouse still works but axis 7 and 8 dont show up but do work as mouse... otherwise i actually cant use the mouse nub at all

**Comment by MNS26** [comment]
without the kernel driver on the latest zen kernel
`Linux ROG-STRIX-SCAR-II 6.1.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:33 +0000 x86_64 GNU/Linux`

nub pointing top right
![image](https://user-images.githubusercontent.com/53867268/210417844-cc402f92-ae2d-4592-b45d-14b3c8f7caa2.png)

nub pointing top left 
![image](https://user-images.githubusercontent.com/53867268/210417918-5aa81e40-9b0e-4066-9bb4-579cb841dec0.png)

nub pointing bottom right
![image](https://user-images.githubusercontent.com/53867268/210418062-e9134d42-8897-4219-b8f7-cfd949a7791d.png)

nub pointing bottom left
![image](https://user-images.githubusercontent.com/53867268/210417975-301aaa46-2e80-4d3f-a2f5-2d415acd3b17.png)

**Comment by nirenjan** [comment]
Yeah, the kernel module was written a while back and it reorders the axis and button maps, so not ideal. I haven't used it in a while, so I'm not sure if there is a bug in the parsing that would cause multiple button presses to get triggered. Best not to use it at all.

**Comment by MNS26** [comment]
this is WITHOUT the kernel module....
WITH the kernel module i dont have that issue

**Comment by nirenjan** [comment]
Uh-oh, that doesn't sound right at all. Could you paste the output of `x52bugreport`? I'm assuming you have the latest release, i.e. 0.3.0

**Comment by MNS26** [comment]
also regarding the button mapping, at least for the x52 pro

```
#define X52_TRIGGER_1       BTN_TRIGGER_HAPPY1      //BTN_TRIGGER_HAPPY1
#define X52_TRIGGER_2       BTN_TRIGGER_HAPPY15     //BTN_TRIGGER_HAPPY2
#define X52_BTN_FIRE        BTN_TRIGGER_HAPPY2      //BTN_TRIGGER_HAPPY3
#define X52_BTN_A           BTN_TRIGGER_HAPPY3      //BTN_TRIGGER_HAPPY4
#define X52_BTN_B           BTN_TRIGGER_HAPPY4      //BTN_TRIGGER_HAPPY5
#define X52_BTN_C           BTN_TRIGGER_HAPPY5      //BTN_TRIGGER_HAPPY6
#define X52_BTN_D           BTN_TRIGGER_HAPPY7      //BTN_TRIGGER_HAPPY7
#define X52_BTN_E           BTN_TRIGGER_HAPPY8      //BTN_TRIGGER_HAPPY8
#define X52_BTN_PINKIE      BTN_TRIGGER_HAPPY6      //BTN_TRIGGER_HAPPY9
#define X52_BTN_T1_UP       BTN_TRIGGER_HAPPY9      //BTN_TRIGGER_HAPPY10
#define X52_BTN_T1_DN       BTN_TRIGGER_HAPPY10     //BTN_TRIGGER_HAPPY11
#define X52_BTN_T2_UP       BTN_TRIGGER_HAPPY11     //BTN_TRIGGER_HAPPY12
#define X52_BTN_T2_DN       BTN_TRIGGER_HAPPY12     //BTN_TRIGGER_HAPPY13
#define X52_BTN_T3_UP       BTN_TRIGGER_HAPPY13     //BTN_TRIGGER_HAPPY14
#define X52_BTN_T3_DN       BTN_TRIGGER_HAPPY14     //BTN_TRIGGER_HAPPY15
#define X52_BTN_CLUTCH      BTN_TRIGGER_HAPPY31     //BTN_TRIGGER_HAPPY16
#define X52_MOUSE_LEFT      BTN_TRIGGER_HAPPY16     //BTN_TRIGGER_HAPPY17
#define X52_MOUSE_RIGHT     BTN_TRIGGER_HAPPY19     //BTN_TRIGGER_HAPPY18
#define X52_MOUSE_FORWARD   BTN_TRIGGER_HAPPY17     //BTN_TRIGGER_HAPPY19
#define X52_MOUSE_BACKWARD  BTN_TRIGGER_HAPPY18     //BTN_TRIGGER_HAPPY20
#define X52_STICK_POV_N     BTN_TRIGGER_HAPPY20     //BTN_TRIGGER_HAPPY21
#define X52_STICK_POV_E     BTN_TRIGGER_HAPPY21     //BTN_TRIGGER_HAPPY22
#define X52_STICK_POV_S     BTN_TRIGGER_HAPPY22     //BTN_TRIGGER_HAPPY23
#define X52_STICK_POV_W     BTN_TRIGGER_HAPPY23     //BTN_TRIGGER_HAPPY24
#define X52_THROT_POV_N     BTN_TRIGGER_HAPPY24     //BTN_TRIGGER_HAPPY25
#define X52_THROT_POV_E     BTN_TRIGGER_HAPPY25     //BTN_TRIGGER_HAPPY26
#define X52_THROT_POV_S     BTN_TRIGGER_HAPPY26     //BTN_TRIGGER_HAPPY27
#define X52_THROT_POV_W     BTN_TRIGGER_HAPPY27     //BTN_TRIGGER_HAPPY28
#define X52_MODE_1          BTN_TRIGGER_HAPPY28     //BTN_TRIGGER_HAPPY29
#define X52_MODE_2          BTN_TRIGGER_HAPPY29     //BTN_TRIGGER_HAPPY30
#define X52_MODE_3          BTN_TRIGGER_HAPPY30     //BTN_TRIGGER_HAPPY31
#define X52_BTN_FUNCTION    BTN_TRIGGER_HAPPY32     //BTN_TRIGGER_HAPPY32
#define X52_BTN_START_STOP  BTN_TRIGGER_HAPPY33     //BTN_TRIGGER_HAPPY33
#define X52_BTN_RESET       BTN_TRIGGER_HAPPY34     //BTN_TRIGGER_HAPPY34
#define X52_BTN_PG_UP       BTN_TRIGGER_HAPPY35     //BTN_TRIGGER_HAPPY35
#define X52_BTN_PG_DN       BTN_TRIGGER_HAPPY36     //BTN_TRIGGER_HAPPY36
#define X52_BTN_UP          BTN_TRIGGER_HAPPY37     //BTN_TRIGGER_HAPPY37
#define X52_BTN_DN          BTN_TRIGGER_HAPPY38     //BTN_TRIGGER_HAPPY38
#define X52_BTN_MFD_SELECT  BTN_TRIGGER_HAPPY39     //BTN_TRIGGER_HAPPY39
```
ive commented your original order and used the order the system has by default

**Comment by MNS26** [comment]
> Uh-oh, that doesn't sound right at all. Could you paste the output of `x52bugreport`? I'm assuming you have the latest release, i.e. 0.3.0

where can i find it?

**Comment by nirenjan** [comment]
You should just be able to run `x52bugreport`.

**Comment by MNS26** [comment]
nope

**Comment by MNS26** [comment]
nvm

**Comment by nirenjan** [comment]
What version are you running?

**Comment by MNS26** [comment]
with or without the modified kernel module loaded

**Comment by MNS26** [comment]
ill do both

**Comment by MNS26** [comment]
without the kernel module loaded
```sh
> x52bugreport
libx52 bugreport
================
Package version: 0.3.0
Build version: v0.3.0
Built on: 2023-01-03T16:56:02+0100
version-info $Id: 9ff692993dd94efda1a444da79e175cf111e631b $

Built against:
==============
libusb API version: 0x01000109
hidapi version: 0.12.0

System versions:
================
libusb: 1.0.26.11724 (http://libusb.info)
hidapi: 0.12.0

System info:
============
Linux 6.1.2-zen1-1-zen x86_64 (#1 ZEN SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:33 +0000)

Device info:
============
Connection failure
~/github/asusctl main !111 ?3 >                                                                                                                                                                                                                                    
```

With the kernel module loaded (modified button layout)
```sh
> x52bugreport
libx52 bugreport
================
Package version: 0.3.0
Build version: v0.3.0
Built on: 2023-01-03T16:56:02+0100
version-info $Id: 9ff692993dd94efda1a444da79e175cf111e631b $

Built against:
==============
libusb API version: 0x01000109
hidapi version: 0.12.0

System versions:
================
libusb: 1.0.26.11724 (http://libusb.info)
hidapi: 0.12.0

System info:
============
Linux 6.1.2-zen1-1-zen x86_64 (#1 ZEN SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:33 +0000)

Device info:
============
Connection failure
~/github/asusctl main !111 ?3 >      
```

**Comment by nirenjan** [comment]
Could you please rerun it with `sudo`?

**Comment by MNS26** [comment]
with module loaded
```sh
> sudo x52bugreport
[sudo] password for noah: 
libx52 bugreport
================
Package version: 0.3.0
Build version: v0.3.0
Built on: 2023-01-03T16:56:02+0100
version-info $Id: 9ff692993dd94efda1a444da79e175cf111e631b $

Built against:
==============
libusb API version: 0x01000109
hidapi version: 0.12.0

System versions:
================
libusb: 1.0.26.11724 (http://libusb.info)
hidapi: 0.12.0

System info:
============
Linux 6.1.2-zen1-1-zen x86_64 (#1 ZEN SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:33 +0000)

Device info:
============
Device ID: vendor 0x06a3 product 0x0762 version 0x2000
Device name: 'Logitech' 'X52 Professional H.O.T.A.S.'
Serial number: '(null)'
```

without the module
```sh
> sudo x52bugreport
libx52 bugreport
================
Package version: 0.3.0
Build version: v0.3.0
Built on: 2023-01-03T16:56:02+0100
version-info $Id: 9ff692993dd94efda1a444da79e175cf111e631b $

Built against:
==============
libusb API version: 0x01000109
hidapi version: 0.12.0

System versions:
================
libusb: 1.0.26.11724 (http://libusb.info)
hidapi: 0.12.0

System info:
============
Linux 6.1.2-zen1-1-zen x86_64 (#1 ZEN SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:33 +0000)

Device info:
============
Device ID: vendor 0x06a3 product 0x0762 version 0x2000
Device name: 'Logitech' 'X52 Professional H.O.T.A.S.'
Serial number: '(null)'
```

**Comment by nirenjan** [comment]
Could you also run `sudo usbhid-dump -m 06a3:0762`

**Comment by MNS26** [comment]
```sh
> sudo usbhid-dump -m 06a3:0762
[sudo] password for noah: 
001:022:000:DESCRIPTOR         1672771511.937843
 05 01 09 04 A1 01 09 01 A1 00 09 30 09 31 15 00
 26 FF 03 75 0A 95 02 81 02 75 02 95 01 81 01 09
 35 15 00 26 FF 03 75 0A 95 01 81 02 09 32 09 33
 09 34 09 36 15 00 26 FF 00 75 08 95 04 81 02 05
 09 19 01 29 27 15 00 25 01 95 27 75 01 81 02 75
 05 95 01 81 01 05 01 09 39 15 01 25 08 35 00 46
 3B 01 66 14 00 75 04 95 01 81 42 05 05 09 24 09
 26 15 00 25 0F 75 04 95 02 81 02 C0 C0
 ```

**Comment by nirenjan** [comment]
That is rather weird, it should have worked fine without the kernel module - I'm wondering if there's a bug in the kernel itself.

**Comment by MNS26** [comment]
hmm  i have no experience on that area

**Comment by MNS26** [comment]
> That is rather weird, it should have worked fine without the kernel module - I'm wondering if there's a bug in the kernel itself.

is there anything i can do to test that?

**Comment by nirenjan** [comment]
I can rewrite the kernel module to send the exact same events as the stock kernel - that should help isolate some of this, as well as ensure that the end user doesn't have to switch between events

**Comment by nirenjan** [comment]
Can you try to use the kernel module in the `update-lkm` branch? This should work exactly like the without module case, except that the report parsing is done by the module and not by the default kernel USB HID layer.

**Comment by nirenjan** [comment]
I don't have my joystick handy, so I can't test it myself at the moment.

**Comment by MNS26** [comment]
it works

**Comment by MNS26** [comment]
it shows axis 7 and 8 but doesnt go nuts

**Comment by MNS26** [comment]
something that i dont understand is that it shows all my inputs double... but it did that without module as well

**Comment by MNS26** [comment]
tho steam seems to to not be happy about it XD

**Comment by MNS26** [comment]
it now shows 3 inputs instead of 2

**Comment by MNS26** [comment]
although i just noticed that the B button now has its light off (didnt touch it in the settingd)

**Comment by MNS26** [comment]
oh... nevermind its broken still

**Comment by MNS26** [comment]
just had to restart the game before it updated

**Comment by MNS26** [comment]
well ill stick with the module in master for now

**Comment by MNS26** [comment]
oh also... for some reason i cant set the B button led to green or amber
B=Green (off)
B=amber (red)
B=red (red)
B=off (off)

**Comment by nirenjan** [comment]
That is weird, was it working earlier? Can you check in a Windows environment if the B green LED works? Amber is just both red and green on at the same time, so an issue affecting just the green LED will exhibit the behavior you see

**Comment by MNS26** [comment]
hmm i will have a look tomorrow

**Comment by MNS26** [comment]
is there a way to set the leds on the fly?

**Comment by nirenjan** [comment]
Yes, you can run `x52ctl config set led b green`

**Comment by MNS26** [comment]
oh cool... im guessing i need sudo for it tho... also one of the wires broke in the joystick (right at the solder joint) but its fixed

**Comment by nirenjan** [comment]
It should work without sudo, but do let me know if it doesn't.

**Comment by MNS26** [comment]
oh cool... im guessing i need sudo for it tho... also one of the wires broke in the joystick (right at the solder joint) but its fixed

**Comment by MNS26** [comment]
nope it doesnt, it gives me a permission denied.

i just added a exception to the sudoers.d and that works but... it has a weird output
![image](https://user-images.githubusercontent.com/53867268/210586542-959d7fae-2d1e-406f-9918-c5b1cfd3b9d4.png)

**Comment by MNS26** [comment]
trying to run without sudo just does this
![image](https://user-images.githubusercontent.com/53867268/210586845-317b9779-a57d-4957-928b-c556e9a0351a.png)

**Comment by MNS26** [comment]
hmm off works but on doesnt... but it also doesnt throw a error
![image](https://user-images.githubusercontent.com/53867268/210591432-acb187b3-eb6d-43b1-be84-4ff26f79fd9e.png)

**Comment by nirenjan** [comment]
Yeah, unfortunately, the config system will accept `off`, `on`, `red`, `amber` and `green`, regardless of which LED is selected, this is a limitation at the moment.

**Comment by MNS26** [comment]
ah... is it a possibility to save it color state before a `off` command is given so `on` just sets the last known color?

**Comment by nirenjan** [comment]
That would be a pretty big change, I'll see what I can do.

**Comment by MNS26** [comment]
oh i forgot to say this earlier...

with the kernel module it seems that after a while steam and (any) game that has controller support on its own crashes and takes steam with it

when launching steam via a terminal for extra info it takes the terminal session with it

**Comment by MNS26** [comment]
oh... 
![image](https://user-images.githubusercontent.com/53867268/210634919-9638c0c3-94ed-4166-b5da-7f789bcaccc4.png)

**Comment by MNS26** [comment]
i would really like to help with the changes, i know C++ and know my way around with C.
i just dont quite know where to start

**Comment by MNS26** [comment]
oh wow.. i realised i wasnt using x52cli but x52ctl well x52cli does work without sudo

**Comment by nirenjan** [comment]
x52cli writes directly to the joystick using libx52, but it can get reset if the daemon restarts. The udev rule allows a user with access to `plugdev` or `input` group (depending on the distro), to write to the joystick without needing root permissions.

**Comment by MNS26** [comment]
im part of the `plugdev` group, i forgot that udev also can set grip permissions.

**Comment by MNS26** [comment]
for whatever reason pressing the up resets the x52

https://user-images.githubusercontent.com/53867268/211122692-9bdb0dea-ed53-4e94-a8c2-ab2807551653.mp4

**Comment by nirenjan** [comment]
Sounds like there may be some short happening, that could cause a reset.

**Comment by MNS26** [comment]
whenever i insmod the saitek kernel module it starts happening

**Comment by MNS26** [comment]
well rebuilding the module seemed to fix it for now

**Comment by MNS26** [comment]
nvm still happens

**Comment by MNS26** [comment]
it also happens when quickly pressing the trigger and releasing the lower button

 release bottom button
 tap trigger
 press bottom button

**Comment by MNS26** [comment]
https://user-images.githubusercontent.com/53867268/211157287-d1565122-3d8f-4e93-8299-a67c2796a0d1.mp4

**Comment by MNS26** [comment]
also i will close this issue since the original issue is gone
